{ pkgs, ... }:
let
  colorschemes = with pkgs.vimPlugins; [
    { plugin = nord-nvim; config = "colorscheme nord"; }
    dracula-vim
    nvcode-color-schemes-vim
  ];
in
{
  xdg.configFile."nvim/lua/config.lua".source = ./config.lua;

  programs.neovim = {
    enable = true;
    viAlias = true;
    vimAlias = true;

    extraConfig = ''
      " Generated by home-manager
      lua require('config')
    '';

    plugins = with pkgs.vimPlugins; [
      vim-polyglot
      #nvim-lspconfig lspsaga-nvim completion-nvim
      #nvim-treesitter
      #telescope-nvim popup-nvim plenary-nvim telescope-fzy-native-nvim
      #which-key-nvim
      #nvim-tree-lua
      #galaxyline-nvim
      #barbar-nvim
      #nvim-colorizer-lua
    ] ++ colorschemes;
  };
}